# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x03\x61pp\"@\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"0\n\x0cUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"/\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\"-\n\x0eProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\"3\n\x0fProductResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"9\n\x13ProductListResponse\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.app.ProductInfo\"6\n\x0bProductInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\"E\n\x0cOrderRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"1\n\rOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"G\n\x13NotificationRequest\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\x12\x11\n\trecipient\x18\x03 \x01(\t\"8\n\x14NotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0e\n\x0c\x45mptyRequest2n\n\x0bUserService\x12/\n\x08Register\x12\x10.app.UserRequest\x1a\x11.app.UserResponse\x12.\n\x05Login\x12\x11.app.LoginRequest\x1a\x12.app.LoginResponse2\x85\x01\n\x0eProductService\x12\x37\n\nAddProduct\x12\x13.app.ProductRequest\x1a\x14.app.ProductResponse\x12:\n\x0bGetProducts\x12\x11.app.EmptyRequest\x1a\x18.app.ProductListResponse2D\n\x0cOrderService\x12\x34\n\x0b\x43reateOrder\x12\x11.app.OrderRequest\x1a\x12.app.OrderResponse2W\n\x13NotificationService\x12@\n\tSendEmail\x12\x18.app.NotificationRequest\x1a\x19.app.NotificationResponseb\x06proto3')



_USERREQUEST = DESCRIPTOR.message_types_by_name['UserRequest']
_USERRESPONSE = DESCRIPTOR.message_types_by_name['UserResponse']
_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINRESPONSE = DESCRIPTOR.message_types_by_name['LoginResponse']
_PRODUCTREQUEST = DESCRIPTOR.message_types_by_name['ProductRequest']
_PRODUCTRESPONSE = DESCRIPTOR.message_types_by_name['ProductResponse']
_PRODUCTLISTRESPONSE = DESCRIPTOR.message_types_by_name['ProductListResponse']
_PRODUCTINFO = DESCRIPTOR.message_types_by_name['ProductInfo']
_ORDERREQUEST = DESCRIPTOR.message_types_by_name['OrderRequest']
_ORDERRESPONSE = DESCRIPTOR.message_types_by_name['OrderResponse']
_NOTIFICATIONREQUEST = DESCRIPTOR.message_types_by_name['NotificationRequest']
_NOTIFICATIONRESPONSE = DESCRIPTOR.message_types_by_name['NotificationResponse']
_EMPTYREQUEST = DESCRIPTOR.message_types_by_name['EmptyRequest']
UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:app.UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

UserResponse = _reflection.GeneratedProtocolMessageType('UserResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:app.UserResponse)
  })
_sym_db.RegisterMessage(UserResponse)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:app.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:app.LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

ProductRequest = _reflection.GeneratedProtocolMessageType('ProductRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:app.ProductRequest)
  })
_sym_db.RegisterMessage(ProductRequest)

ProductResponse = _reflection.GeneratedProtocolMessageType('ProductResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:app.ProductResponse)
  })
_sym_db.RegisterMessage(ProductResponse)

ProductListResponse = _reflection.GeneratedProtocolMessageType('ProductListResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTLISTRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:app.ProductListResponse)
  })
_sym_db.RegisterMessage(ProductListResponse)

ProductInfo = _reflection.GeneratedProtocolMessageType('ProductInfo', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTINFO,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:app.ProductInfo)
  })
_sym_db.RegisterMessage(ProductInfo)

OrderRequest = _reflection.GeneratedProtocolMessageType('OrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORDERREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:app.OrderRequest)
  })
_sym_db.RegisterMessage(OrderRequest)

OrderResponse = _reflection.GeneratedProtocolMessageType('OrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _ORDERRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:app.OrderResponse)
  })
_sym_db.RegisterMessage(OrderResponse)

NotificationRequest = _reflection.GeneratedProtocolMessageType('NotificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:app.NotificationRequest)
  })
_sym_db.RegisterMessage(NotificationRequest)

NotificationResponse = _reflection.GeneratedProtocolMessageType('NotificationResponse', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:app.NotificationResponse)
  })
_sym_db.RegisterMessage(NotificationResponse)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:app.EmptyRequest)
  })
_sym_db.RegisterMessage(EmptyRequest)

_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
_PRODUCTSERVICE = DESCRIPTOR.services_by_name['ProductService']
_ORDERSERVICE = DESCRIPTOR.services_by_name['OrderService']
_NOTIFICATIONSERVICE = DESCRIPTOR.services_by_name['NotificationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERREQUEST._serialized_start=22
  _USERREQUEST._serialized_end=86
  _USERRESPONSE._serialized_start=88
  _USERRESPONSE._serialized_end=136
  _LOGINREQUEST._serialized_start=138
  _LOGINREQUEST._serialized_end=185
  _LOGINRESPONSE._serialized_start=187
  _LOGINRESPONSE._serialized_end=234
  _PRODUCTREQUEST._serialized_start=236
  _PRODUCTREQUEST._serialized_end=281
  _PRODUCTRESPONSE._serialized_start=283
  _PRODUCTRESPONSE._serialized_end=334
  _PRODUCTLISTRESPONSE._serialized_start=336
  _PRODUCTLISTRESPONSE._serialized_end=393
  _PRODUCTINFO._serialized_start=395
  _PRODUCTINFO._serialized_end=449
  _ORDERREQUEST._serialized_start=451
  _ORDERREQUEST._serialized_end=520
  _ORDERRESPONSE._serialized_start=522
  _ORDERRESPONSE._serialized_end=571
  _NOTIFICATIONREQUEST._serialized_start=573
  _NOTIFICATIONREQUEST._serialized_end=644
  _NOTIFICATIONRESPONSE._serialized_start=646
  _NOTIFICATIONRESPONSE._serialized_end=702
  _EMPTYREQUEST._serialized_start=704
  _EMPTYREQUEST._serialized_end=718
  _USERSERVICE._serialized_start=720
  _USERSERVICE._serialized_end=830
  _PRODUCTSERVICE._serialized_start=833
  _PRODUCTSERVICE._serialized_end=966
  _ORDERSERVICE._serialized_start=968
  _ORDERSERVICE._serialized_end=1036
  _NOTIFICATIONSERVICE._serialized_start=1038
  _NOTIFICATIONSERVICE._serialized_end=1125
# @@protoc_insertion_point(module_scope)
