# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = "1.70.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class UserServiceStub(object):
    """User Authentication Service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
            "/app.UserService/Register",
            request_serializer=service__pb2.UserRequest.SerializeToString,
            response_deserializer=service__pb2.UserResponse.FromString,
            _registered_method=True,
        )
        self.Login = channel.unary_unary(
            "/app.UserService/Login",
            request_serializer=service__pb2.LoginRequest.SerializeToString,
            response_deserializer=service__pb2.LoginResponse.FromString,
            _registered_method=True,
        )


class UserServiceServicer(object):
    """User Authentication Service"""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Register": grpc.unary_unary_rpc_method_handler(
            servicer.Register,
            request_deserializer=service__pb2.UserRequest.FromString,
            response_serializer=service__pb2.UserResponse.SerializeToString,
        ),
        "Login": grpc.unary_unary_rpc_method_handler(
            servicer.Login,
            request_deserializer=service__pb2.LoginRequest.FromString,
            response_serializer=service__pb2.LoginResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "app.UserService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("app.UserService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class UserService(object):
    """User Authentication Service"""

    @staticmethod
    def Register(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/app.UserService/Register",
            service__pb2.UserRequest.SerializeToString,
            service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Login(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/app.UserService/Login",
            service__pb2.LoginRequest.SerializeToString,
            service__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class ProductServiceStub(object):
    """Product Management Service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddProduct = channel.unary_unary(
            "/app.ProductService/AddProduct",
            request_serializer=service__pb2.ProductRequest.SerializeToString,
            response_deserializer=service__pb2.ProductResponse.FromString,
            _registered_method=True,
        )
        self.GetProducts = channel.unary_unary(
            "/app.ProductService/GetProducts",
            request_serializer=service__pb2.PaginationRequest.SerializeToString,
            response_deserializer=service__pb2.ProductListResponse.FromString,
            _registered_method=True,
        )


class ProductServiceServicer(object):
    """Product Management Service"""

    def AddProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "AddProduct": grpc.unary_unary_rpc_method_handler(
            servicer.AddProduct,
            request_deserializer=service__pb2.ProductRequest.FromString,
            response_serializer=service__pb2.ProductResponse.SerializeToString,
        ),
        "GetProducts": grpc.unary_unary_rpc_method_handler(
            servicer.GetProducts,
            request_deserializer=service__pb2.PaginationRequest.FromString,
            response_serializer=service__pb2.ProductListResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "app.ProductService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("app.ProductService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Product Management Service"""

    @staticmethod
    def AddProduct(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/app.ProductService/AddProduct",
            service__pb2.ProductRequest.SerializeToString,
            service__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetProducts(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/app.ProductService/GetProducts",
            service__pb2.PaginationRequest.SerializeToString,
            service__pb2.ProductListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class OrderServiceStub(object):
    """Order Processing Service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrder = channel.unary_unary(
            "/app.OrderService/CreateOrder",
            request_serializer=service__pb2.OrderRequest.SerializeToString,
            response_deserializer=service__pb2.OrderResponse.FromString,
            _registered_method=True,
        )


class OrderServiceServicer(object):
    """Order Processing Service"""

    def CreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateOrder": grpc.unary_unary_rpc_method_handler(
            servicer.CreateOrder,
            request_deserializer=service__pb2.OrderRequest.FromString,
            response_serializer=service__pb2.OrderResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "app.OrderService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("app.OrderService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Order Processing Service"""

    @staticmethod
    def CreateOrder(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/app.OrderService/CreateOrder",
            service__pb2.OrderRequest.SerializeToString,
            service__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class NotificationServiceStub(object):
    """Notification Service (Kafka-Driven)"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendEmail = channel.unary_unary(
            "/app.NotificationService/SendEmail",
            request_serializer=service__pb2.NotificationRequest.SerializeToString,
            response_deserializer=service__pb2.NotificationResponse.FromString,
            _registered_method=True,
        )


class NotificationServiceServicer(object):
    """Notification Service (Kafka-Driven)"""

    def SendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendEmail": grpc.unary_unary_rpc_method_handler(
            servicer.SendEmail,
            request_deserializer=service__pb2.NotificationRequest.FromString,
            response_serializer=service__pb2.NotificationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "app.NotificationService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "app.NotificationService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """Notification Service (Kafka-Driven)"""

    @staticmethod
    def SendEmail(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/app.NotificationService/SendEmail",
            service__pb2.NotificationRequest.SerializeToString,
            service__pb2.NotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
